apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    name: voting-app-pod
    app: demo-voting-app
spec:
  replicas: 1
  selector: 
    matchLabels:
      name: voting-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: voting-all-pod
      labels: 
        name: voting-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: voting-app
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80