apiVersion: batch/v1
kind: Job
metadata:
  name: mth-aa-job
spec:
  template:
    spec:
      containers:
        - name: math-add
          image: ubuntu
          command: ["expr", "3", "+", "2"]
      restartPolicy: Never
