apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    run: busybox
spec:
  containers:
  - args:
    - bin/sh
    - -c
    - ls; sleep 3600
    image: busybox
    name: busybox1
  - args:
    - bin/sh
    - -c
    - echo Hello World; sleep 3600
    image: busybox
    name: busybox2
  - args:
    - bin/sh
    - -c
    - echo this is the third container; sleep 3600
    image: busybox
    name: busybox3
  restartPolicy: Never